### ISSUE TITLE
Yo I got a problem 

### ISSUE THREAD

**Issue by paigetoma** [ragozzine/hugozzine#20]
tktktktktktkktkt

**problem** 

Here's the link: https://infosphere.alley.ws/alley/ 

Screenshot: 
![Screen Shot 2021-03-10 at 11 05 06 AM](https://user-images.githubusercontent.com/53276162/111210181-50ff3c80-85a3-11eb-9581-595d7c70de20.png)

**Comment by ragozzine** [comment]
Sure we'll take a look!

**Comment by ragozzine** [comment]
Sorry it works after all. It was all a dream.
